### ISSUE TITLE
Missing Makefile.in

### ISSUE THREAD

**Issue by rrthomas** [martenjj/drawview#2]
Personally, I'd not check files like `configure` and `Makefile.in` into git; rather, I'd require that users run `autoreconf` to generate them.

**Comment by rrthomas** [comment]
However, this appears not to be the only problem here, as running `autoreconf -i` does not generate `Makefile.in`, but complains:

```
configure.ac:477: error: required file 'po/Makefile.in' not found
Makefile.am:33: error: required directory ./po does not exist
```

**Comment by rrthomas** [comment]
Jolly good, this works now. However, you now have `configure` in git but not `Makefile.in`: need either to remove the former, or add the latter!

**Comment by martenjj** [comment]
Just noticed that when doing a fresh clone and test, hopefully now fixed.

There seems to be some discussion as to whether autoconf-generated stuff should be in the source tree.  It normally was in the days of download tarballs, but then I suppose that then having to use autoreconf was an unfamiliar step and the install instructions just said 'download, untar then configure'.  Now I suppose that we can assume that anyone with the knowledge to use git would be able to perform that stage.  Assuming that they have the full set of autotools installed on their system, of course... I use Gentoo which means that my system is completely different to anyone else's, so I don't know if standard distros have them included as standard.

My intention for the future is to port to Qt 5 (and optionally KDE Frameworks), which would mean moving to cmake.  So autotools' days in DrawView are numbered anyway...

**Comment by rrthomas** [comment]
My perspective is that it's more a question of expecting users to have autotools installed (or to be able to install them), and treating `configure` &c. as generated files (hence not putting them in git). I'd still expect to see an instruction to run `autoreconf` or a suitable `autogen.sh` or `bootstrap` script in the `README`. But as you say, if you're likely to move away from autotools, the solution doesn't really matter.
