### ISSUE TITLE
Build from clean checkout fails

### ISSUE THREAD

**Issue by rrthomas** [martenjj/drawview#3]
`configure` works fine, then:

```
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/rrt/repo/drawview/missing aclocal-1.15 
```

/home/rrt/repo/drawview/missing: line 81: aclocal-1.15: command not found
    WARNING: 'aclocal-1.15' is missing on your system.
             You should only need it if you modified 'acinclude.m4' or
             'configure.ac' or m4 files included by 'configure.ac'.
             The 'aclocal' program is part of the GNU Automake package:
             http://www.gnu.org/software/automake
             It also requires GNU Autoconf, GNU m4 and Perl in order to run:
             http://www.gnu.org/software/autoconf
             http://www.gnu.org/software/m4/
             http://www.perl.org/
    make: **\* [aclocal.m4] Error 127

**Comment by martenjj** [comment]
Just tried that here in a clean clone and it tries to do that same 'missing', except that it succeeds.  But then I do have aclocal-1.15 installed.  So maybe the user does need the full set of autotools after all...

**Comment by rrthomas** [comment]
I think the problem here is not checking in aclocal.m4.

That's the thing: if you're going to check stuff in, you have to check everything in!

**Comment by martenjj** [comment]
Just tried that - copying aclocal.m4 into a clean clone - and also touching configure to make sure that it is newer than everything else.  But it still tries to run the 'missing aclocal' command (and succeeds).

Guess the solution is exactly that:  remove all the generated files and mandate that the user has autotools.

**Comment by rrthomas** [comment]
It was probably something else missing; but I've been doing "clean git" for years now, so the "all files" solution escapes me. Indeed, probably easier to remove everything and require autoreconf.

**Comment by martenjj** [comment]
Have done exactly that...

**Comment by rrthomas** [comment]
Thanks!
