### ISSUE TITLE
Command line conversion

### ISSUE THREAD

**Issue by Sembiance** [martenjj/drawview#4]
Awesome app!

I'd LOVE to see a command line app that can convert to SVG with `drawview-convert <input> <out.svg>`  to simply convert the input file directly to an SVG file, with no GUI.

I've currently hacked it up the code on my side to do this, but it's pretty messy code and not worthy of a pull request.

**Comment by Sembiance** [comment]
In case the author doesn't have the time for such a feature or chooses not to implement it... if someone else finds this issue and wants an export feature, I've attached to this comment the patch file.
It basically just adds a new CLI option `-e, --export-directory <directory>  Export all input files as SVG into`
When set, it will automatically export all files you passed in on CLI  as SVG files to the export-directory specified, then exit. So the GUI still shows up and everything, but it works.

[export.patch.txt](https://github.com/martenjj/drawview/files/7272038/export.patch.txt)

**Comment by martenjj** [comment]
Thanks for the patch, and I may well implement such a facility - possibly to PDF or PS as well as SVG.

Note to any possible implementers:   split out the bottom half of DrawView::fileExport() from "QPaintDevice *device" through to "delete device" into a new function, and use it for both GUI and batch exporting.
